api:
  resource: "@ApiBundle/Controller/"
  type:     annotation
  prefix:   /api

api_login_check:
  path:     /api/login_check

app:
  resource: "@AppBundle/Controller/"
  type:     annotation

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
