security:
  encoders:
    ApiBundle\Entity\User: bcrypt

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  providers:
    user_provider:
      entity:
        class: ApiBundle:User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    doc:
      pattern: ^/api/doc
      security: false

    login:
      pattern:  ^/api/login
      stateless: true
      anonymous: true
      provider: user_provider
      form_login:
        check_path:               /api/login_check
        success_handler:          lexik_jwt_authentication.handler.authentication_success
        failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false

    main:
      pattern: ^/
      anonymous: ~
      form_login:
          login_path: app_security_login
          check_path: app_security_login
      logout:
        path:   /logout
        target: /

  access_control:
    - { path: ^/,          roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/admin,     roles: [IS_AUTHENTICATED_FULLY] }
    - { path: ^/api,       roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
