security:
  encoders:
    Symfony\Component\Security\Core\User\User: bcrypt
    ApiBundle\Entity\User: bcrypt

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  providers:
    user_provider:
      entity:
        class: ApiBundle:User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    doc:
      pattern: ^/api/doc
      security: false

    main:
      pattern: ^/
      anonymous: ~
      form_login:
          login_path: app_security_login
          check_path: app_security_login
      logout:
        path:   /logout
        target: /

  access_control:
    - { path: ^/,          roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
    - { path: ^/admin,     roles: [IS_AUTHENTICATED_FULLY] }
    - { path: ^/api,       roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
