services:
  api.service.user:
    class: ApiBundle\Services\UserService
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "api.mapper.user"

  api.service.album:
    class: ApiBundle\Services\AlbumService
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@api.mapper.album"

  api.service.music:
    class: ApiBundle\Services\MusicService
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@api.mapper.music"
