services:
  api.service.user:
    class: ApiBundle\Services\UserService
    arguments: ["@doctrine.orm.default_entity_manager"]

  api.service.album:
    class: ApiBundle\Services\AlbumService
    arguments:
      - "@doctrine.orm.default_entity_manager"
      - "@api.mapper.album"
